export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
eval "python -V"
eval "source /media/mint/85f78c06-a96e-4020-ac36-9419b7e456db/mint/root/tools/pyenv/3.6.1/venv/webapi/bin/activate"
eval "python hello.py"
eval "python 0.py"
eval "python 1.py"
eval "python 2.py"
